"""Add field to exclude posts from embedding computation

Revision ID: af85c27a1abc
Revises: 9218ec56ee4d
Create Date: 2024-12-09 16:36:13.170849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af85c27a1abc"
down_revision: Union[str, None] = "9218ec56ee4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("exclude_for_embedding", sa.Boolean(), nullable=True, default=False, server_default="FALSE")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "exclude_for_embedding")
    # ### end Alembic commands ###
